# Generated by Django 5.1.1 on 2024-10-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_notification_order_review_order_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
