# Generated by Django 5.1.1 on 2024-10-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/', verbose_name='Attach Photos'),
        ),
    ]
